spring:
  profiles:
    active: test
  application:
    name: Compensations API
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5434/compensation
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
rabbitmq:
  compensations:
    created:
      queue: compensations.create
      exchange: compensations_create_exchange
      routingKey: compensations_create_routingKey
    failed:
      queue: compensations.create.failed
      exchange: compensations_create_failed_exchange
      routingKey: compensations_create_failed_routingKey

server:
  port: 8080
  servlet:
    context-path: /api/v1
